using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FoodParser
{
    public static class Proverb
    {
        private static string[] _proverbs =
        {
            "Običaji starine, so ščit domovine.",
            "Ljubo doma, kdor ga ima;kdor ga nima, pa za njim kima.",
            "Boljša domača gruda, kot na tujem zlata ruda.",
            "Čuvajmo kot zlato rudo, milo nam domačo grudo!",
            "Ne z besedo puhlo, ki v ustih mine, z deli kažimo ljubezen do domovine!",
            "Brez žrtev ni svobode, mar narod naš drugače je dobode!",
            "Bojujmo vsi se pod zastavo: Vse za narodovo pravo!",
            "Kdor za narod naš se ne žrtvuje, naj Slovenec se ne imenuje!",
            "Dokler hud sovrag ogroža meje, bramba nam v dolžnost se šteje!",
            "Hajdmo pogumno v boj za naše brate, za svobodo domovine naše zlate!",
            "Mali smo narod; v njem neznanska silna moč. Ne, ne bo nas zagrnila tujstva noč!",
            "Na delo, slovenske vse hčere, sinovi, da rešimo rod svoj pred tujstva okovi!",
            "S hrabrim srcem, z dušo vneto v boj za domovino sveto!",
            "Mladina naša, kje so tvoji vzori? Za narod svoj žrtvuj in se bori!",
            "Gospodarji zemlji naši hočemo biti, tujci grabežljivi  je ne smejo v plen dobiti!",
            "Prva nam mar, nam vsekdar narodna stvar!",
            "Sovražnikov naval narašča od leta do leta, zaustavimo ga, na delo slovenska četa!",
            "Kolikor hujša nevarnost nam preteča, toliko naj požrtvovalnost naša veča!",
            "Ne ženi se nikdar iz naroda!",
            "Ne pusti, da bi grabežljivi tujec kradel in manjšal slovenski svet!",
            "Noben narod se ne more pravično soditi v tujem jeziku, po tujih, njemu nerazumljivih postavah!",
            "Na starem ognjišču rado gori.",
            "Povsod je lepo, a doma je najlepše.",
            "Veliko mesto – velika samota.",
            "Vsakomur se svoje najlepše zdi.",
            "Svoja hišica – svoja voljica.",
            "Bolje prvi na vasi kakor zadnji v mestu.",
            "Domače perilo naj se doma pere.",
            "Kdor se doma poniža, ga na tujem pohodijo.",
            "Kdor se s tujim jezikom pači, z domačim berači.",
            "Ne vemo, kaj imamo, dokler ne izgubimo.",
            "Bolje je malo lastnega, kakor mnogo tujega.",
            "Težko svojemu brez svojega.",
            "Ne zanesi se na tujo kašo pri svoji doma.",
            "Kadar izgubiš kar imaš, tega vrednost spoznaš.",
            "Starih šeg ne vseh zatreti, novih pa ne vseh sprejeti.",
            "Tuja šega domačo zbega.",
            "Iz medene doline bežiš, pa si v štrukljev hrib želiš.",
            "Kdor po tujem hlepi, svoje izgubi.",
            "Neumen je tisti ptič, ki se sramuje svojega gnezda.",
            "Kdor preveč obljublja, zaupanje izgublja.",
            "Obljuba dela dolg.",
            "Dejanja so glasnejša od besed.",
            "Besede mikajo, zgledi vlečejo.",
            "Kadar beseda ne zaleže, se palica vreže.",
            "Dosti besed – malo prida.",
            "Beseda izgovorjena, ne vrne se nobena.",
            "Beseda lahko močneje udari kot pest.",
            "Lepa beseda nikomur ne preseda.",
            "Ni vseeno, kdo kaj reče.",
            "Bolje je dvakrat vprašati, kot enkrat preslišati.",
            "Vola primeš za roge, človeka za besedo.",
            "Kdor te na skrivaj obrekuje, se te boji;kdor se ti prilizuje, te zaničuje.",
            "Laskava beseda je rada zaseda.",
            "Modra ušesa se ne zmenijo za neumne besede.",
            "Od vsake klevete nekaj ostane.",
            "Poln želodec, prazne govorice.",
            "Da se resnica prav spozna, treba je slišati dva zvona.",
            "Strupen jezik je nevarnejši od strupene kače.",
            "Kjer vsi govorijo, nihče ne posluša.",
            "Kdor vpraša, ne zaide.",
            "Kdor govori, kar se mu zdi, mora slišati, česar ne želi.",
            "Jezik z mošnjo raste.",
            "Laž hodi po eni nogi.",
            "Laž je kakor šilo v žepu;prej ali slej se izda.",
            "Hiša razdeljena,razpada kakor razpuščena.",
            "Išči napake, pa boš našel skrbi!",
            "Ogibaj se kozla od spredaj,konja od zadaj,zlega človeka pa od vseh strani.",
            "Kdor je predolgo pri hiši,ga vrata po petah tolčejo.",
            "Vrag vedno pride po svoje.",
            "Cesar lahko postane vsak berač,če ga le ljudstvo izvoli.",
            "Dekla se po gospodinji vrže,ne gospodinja po dekli.",
            "Kjer nobene postave ni, tam veljajo le pesti.",
            "Drva je treba pripraviti, kadar so češnje zrele.",
            "Strog učitelj naredi dobrega učenca.",
            "Gozd je kmetova hranilnica.",
            "Prazne buče močno donijo.",
            "Kdor ne hrani mačke, hrani miši.",
            "Na žlico medu se ujame več muh kot v sod kisa.",
            "Vsak po sebi vatle meri.",
            "Sosedov nič bolj ne zbliža kot dobra ograja.",
            "Še lonci na polici se skregajo, pa bi se ljudje ne.",
            "Ogenj in voda dobro služita, a slabo gospodarita.",
            "Več žensk je v hlačah kot v krilih.",
            "Zaradi ene muhe si pajek ne splete mreže.",
            "Če baba nima metle, pa z jezikom pometa.",
            "Kjer se veliki prepirajo, mali umirajo.",
            "Če je več mlinarjev, je manj moke.",
            "Pokrij se samo toliko, kolikor si dolg.",
            "Ne beli si las, kje boš dobil uzdo, ko še nimaš konja.",
            "Podarjenemu konju se ne gleda v zobe.",
            "Kjer sta dva petelina na enem dvorišču, je vrišč.",
            "Kjer ljudje v miru žive, jim ptice rajsko žvrgole.",
            "Predebela svinja je sama kriva svoje smrti.",
            "Dvaintrideset zob ne opravi nič proti enemu samemu jeziku.",
            "Nevesta bogata je rada rogata.",
            "Kdor goni dva zajca, nobenega ne ujame.",
            "Dokler lipa cvete, ji ne manjka čebel.",
            "Dokler je rosa, reže sama kosa.",
            "Babe se še hudič boji.",
            "Bodi vragu dober, s peklom ti poplača.",
            "Nered in prepir sta pogube izvir.",
            "Molčati ni nobena umetnost, je pa težko.",
            "Jezik je dobro zagrajen, pa vendar uhaja.",
            "Malo počakaj, da se beseda uleti!",
            "Za prepir sta potrebna dva.",
            "Ni že vsak, ki nosi hlače, mož.",
            "Kdor se za tele pravda, kravo zapravi.",
            "Oblast je slast in past.",
            "Ako hočeš spoznati človeka, daj mu oblast.",
            "Iz te kože ne moremo v drugo.",
            "Dobro ni vzeti iz mlina praseta in iz krčme dekleta.",
            "Blato lahko umaže dragulj, ne more pa ga spremeniti v blato.",
            "Lahko je s polnim trebuhom post hvaliti.",
            "Toliko časa je boter, dokler je bokal moker.",
            "Prazen žakelj ne stoji pokonci.",
            "Navada se vrača rada.",
            "Kmet seje, krčmar žanje.",
            "Lepe krčme ne zida krčmar, ampak pivci.",
            "Noben žep ni tako nasmeten, da ga ne bi krčmar počistil.",
            "V vinu se jih več utopi kakor v vodi.",
            "Nesreča nikoli ne počiva.",
            "Kakor se koscem streže, tako jim kosa reže.",
            "Polž roge pokaže, kadar ga nihče ne vidi.",
            "Dobremu človeku je težko par dobiti.",
            "Lačna vrana se ne zmeni za strašilo.",
            "Pijača vleče denar iz žepa, pamet pa iz glave.",
            "Nobena juha se ne poje tako vroča, kakor se skuha.",
            "Slaba gospodinja je kakor kokoš;več ko ima, več razmeče.",
            "Volk dlako menja, nravi pa nikoli.",
            "Kjer je dim, je tudi ogenj.",
            "Riba pri glavi smrdi.",
            "Uboga hiša, kjer koklje pojejo in petelin molči.",
            "Ne prodajaj kožuha, dokler medved še v brlogu spi.",
            "Vsak lončar svoje lonce hvali.",
            "Vsaka šola nekaj stane.",
            "Izza panja je lahko streljati.",
            "Po toči zvoniti je prepozno.",
            "Če veter ne bi raztrgal pajčevin, bi svet prepredle.",
            "Če bi bil vedež, ne bi bil revež.",
            "Redki so prijatelji v stiski.",
            "Pes leži na slami; sam je ne je, drugim je pa tudi ne da.",
            "Stari vrabec se ne boji strašila, ampak tistega, ki je strašilo nastavil.",
            "Dobro živi, komur je malo zadosti.",
            "V coklah ne hodi zajcev lovit!",
            "Mornarski kruh ima sedem skorij.",
            "Na domačem gnojišču je še petelin junak.",
            "Kar za lešnik pridobiš, za oreh izgubiš.",
            "Kdor hoče hvaljen biti, mora umreti,kdor hoče opravljan biti, se mora oženiti.",
            "Kogar voda objema, se slame oprijema.",
            "Ko ti začne slaba presti, se te vsi žele otresti.",
            "Ko čevelj škorenj rata, ne pozna ne sestre ne brata.",
            "Česar oko ne vidi, tega si srce ne želi.",
            "Po zaraslih stezah ni mogoče nazaj.",
            "Jabolka so najbolj cenjena, ko jih zmanjka.",
            "Vsak raj ima svojo kačo.",
            "Tisti denar je resničen, ki ga človek v pesti drži.",
            "Nehvaležnost in smeti se povsod najdejo.",
            "Pamet je boljša kot žamet.",
            "Kdor veliko misli, malo govori.",
            "Kadar strast govori, pameti ni.",
            "Modra beseda, polna skleda.",
            "Lisica je volku služila, pa je kožuh izgubila.",
            "Ko lisica spi, najlaže kure ulovi.",
            "Ne hvali dneva pred večerjo.",
            "Stara mera, stara vera.",
            "Kdor se na druge zanaša, v situ vodo prenaša.",
            "Dobra vaga v nebesa pomaga.",
            "Kdor kosi od kraja, psa pusti, naj laja.",
            "Ob žetvi kmet le toliko zaspi, da glavo čez prag položi.",
            "Čim lepše katera otep veže, tem lepšega ženina dobi.",
            "Hitro začeto je dvakrat prijeto.",
            "Delo hvali mojstra.",
            "Ceneno blago je vedno najdražje.",
            "Kdor ne izmeri sebe, ga izmerijo drugi.",
            "Osel gre samo enkrat na led.",
            "Če dolgo sekaš, mora pasti tudi najdebelejši hrast.",
            "Žene, pipca in konja ne posojaj.",
            "Žena drži pri hiši tri vogle in še pri četrtem možu pomaga.",
            "Može gradijo hiše, žene ustvarjajo dom.",
            "Če ni, tudi ujma ne vzame.",
            "Če vrag omaga, mu baba pomaga.",
            "Na nebu ni dveh sonc, v trdni hiši ne dveh gospodarjev.",
            "Kdor zjutraj dolgo leži, žgance zamudi.",
            "Na nizkega osla se lahko vsakdo povzpne.",
            "Ni bolj praznega človeka, kot je tisti, ki je sam sebe poln.",
            "Pameten kovač ima obenem več želez v ognju.",
            "Kuj železo, dokler je vroče.",
            "Samo neumni je vedno zadovoljen s seboj.",
            "Visoko glavo nosi prazen klas.",
            "Majhno je človekovo srce, a neizmerne so njegove želje.",
            "Dvema pastirjema volk lažje ovco ukrade kot enemu.",
            "Z gospodo je lahko češnje brati, a težko zobati.",
            "Bolje funt pameti, kakor cent moči.",
            "Zrno do zrna pogača, kamen na kamen palača.",
            "Kdor dolgo spi, obira kosti.",
            "Kar človek sam prisluži, najbolje obrne.",
            "Bolezen pridirja na konju in odide peš.",
            "Pomlad in mladost sta si podobni.",
            "V očeh mladih je čistost, v očeh starih je luč.",
            "Starost ne pride sama.",
            "V mladosti so solze brez bolečin, v starosti bolečine brez solz.",
            "Prevelika sila se sama uje.",
            "Jabolko, ki pozneje dozori, se dalj drži.",
            "Mlado drevo se obrezuje, staro ne.",
            "Vrlina ne cveti, a bogate sadove rodi.",
            "Reko se zajezi, ko je še potok.",
            "Če kdo koga s tinto privije, se težko izvije.",
            "Stare vrane ne pobirajo črvov blizu brane.",
            "Kdor ne ve, da je bedak, je dvakrat bedak.",
            "Ne boj se cesarja, ampak tistih, ki njegove zakone obračajo.",
            "Brez glave storjeno, gotovo skaženo.",
            "Več je vredna ena priča, ki je videla, kakor tri, ki so slišale.",
            "Več postav, več zmešnjav, več težav.",
            "Bodi zmeren pri delu, jedi in pijači.",
            "Kdor se med otrobe meša, ga svinje požro.",
            "Labod leta vse življenje nad blatom in vendar ostane bel.",
            "Če golob med orle zaide, gotovo smrt najde.",
            "Vsakdo doseže svoj konec, a cilja ne vedno.",
            "Nikdar ni bilo tako, da ni bilo kako in nikdar ne bo tako, da ne bo kako.",
            "Zarečenega kruha se največ poje.",
            "Ne brani vrabčku piti iz studenca, saj ga ne bo popil!",
            "Kdor zna lajati, mu ni treba znati govoriti.",
            "Poleti je treba imeti v glavi, pozimi pa v hlevu.",
            "Kdor se je naredil za osla, naj se ne čudi, če ga drugi jahajo.",
            "Krava se pri gobcu molze.",
            "Kokošji let ne traja dolgo.",
            "Kadar se z blatom bojujem, vem le eno;če zmagam ali ne, vedno se umažem.",
            "Kadar je žakelj poln, se razveže.",
            "Kadar kupuješ, ne reci, da potrebuješ.",
            "Kjer glad mori lenuha, pridni dosti najde kruha.",
            "Ko denar poide, pamet pride.",
            "Pametnemu malo besed veliko pove.",
            "Komur ni mogoče svetovati, mu ni mogoče pomagati.",
            "Pokornih glav sablja ne seka.",
            "Smrt nič ne vpraša, po svoje odnaša.",
            "Kdor živ da, sam da;po smrti drugi delijo.",
            "Človek se mora po ljudeh ravnati, ne ljudje po človeku.",
            "Bolje stare modrosti, kot nove norosti.",
            "Česar v glavi ni, peta nadomesti.",
            "Vodo se naučimo ceniti šele, ko se vodnjak posuši.",
            "Ne pljuj v nobeno štirno;saj ne veš, pri kateri te bo žejalo!",
            "Visokim smrekam vihar vrhove lomi.",
            "Drevesu okrepiš korenine, če mu odrežeš kilave veje.",
            "Samo tisto drevo je čvrsto, ki ga vetrovi često tepo.",
            "Voda ni nikoli tako čista,da se ne bi mogla skalitiin nikoli tako kalna,da se ne bi mogla zbistriti.",
            "Tudi najmočnejši veter ne zgane vode v vodnjaku.",
            "Ko padeš v vodo, je prepozno, da bi se učil plavati.",
            "Ne pričakuj sence od drevesa, včeraj zasajenega!",
            "Še tako dolga pot se začne s prvim korakom.",
            "Počasi se daleč pride, naglica koristi samo zajcem.",
            "Mlado drevo se da zravnati, staro se zlomi.",
            "S starega drevja sadje samo pade.",
            "Pametnega kočijaža tudi slepi konj pripelje domov.",
            "Kdor ne pomisli, kam gre, potem nazaj ne ve.",
            "Ogenj in slama naj bosta sama.",
            "Dva kresilna kamna iskre delata.",
            "Eno pokvarjeno jajce pokvari celo peko.",
            "Ne klesti drevja pod katerim počivaš.",
            "Dan se po jutru pozna.",
            "Iz osla ne narediš jahalnega konja, pa če ga še tako dresiraš.",
            "Kdor nima pravice, išče skrite stezice.",
            "Boljše je shranjeno jajce, kot sneden vol.",
            "Kdor želi vrtnico sprejeti, mora sprejemati tudi trnje.",
            "Kdor hoče druge vneti, mora sam goreti.",
            "Veliko besedi malo naredi.",
            "Od besed do dejanja se človeku mnogo sanja.",
            "Čas setve še ni čas žetve.",
            "Žel boš kar boš sejal.",
            "Lačni niso izbirčni.",
            "Jej malo, pa to dobro.",
            "Hudo je biti priklenjen, pa čeprav z zlato verigo.",
            "Kdor ni okusil bridkega, ne pozna sladkega.",
            "Lačen trebuh nima ušes.",
            "Up je kruh bednika.",
            "Ne vračaj se h kosti, ki si jo že nehal jesti.",
            "Poln želodec se smeji.",
            "Danes gosti-jutri posti.",
            "Kjer je žgal ogenj, ostane brazgotina.",
            "Prevzetnost in napuh ne vesta, kako se služi kruh.",
            "Kdor ljubi denar kakor obraz, izgubi oboje.",
            "Če se kamen premika, se ne obrase z mahom.",
            "Črno na belem nikdar ne izgine.",
            "Kako se v gozd kliče, tako odmeva.",
            "Vsaka pesem se enkrat izpoje.",
            "Daleč od oči, daleč od srca.",
            "Česar je polno srce, rado iz ust gre.",
            "Vsaka voda je pri izviru čista.",
            "Varuj se ga,ki spredaj z medom maže,zadaj figo kaže.",
            "Če v Prosincu ni snega,ga Mali traven da.",
            "Kadar Anton (17.1.)z dežjem prihaja,se dolgo potem zemlja napaja.",
            "Če v Prosincu drevje od mraza poka,bo sadja jeseni in moka.",
            "Prosinec mili – bog se usmili.",
            "Če bo Prosinca mokrilo,bo polje in grozdje slabo rodilo.",
            "V Prosincu toplota,v Svečanu mrzlota.",
            "Če Prosinca ne zmrzuje, ne sneži,rad Sušec to naredi.",
            "Če za tri kralje (6.1.) jasen dan bo,za dolgo zimo hrani seno.",
            "Če Vincenca (22.1.) sonce peče,dobro vince dozori,ki po grlu gladko teče,motne dela ti oči.",
            "Svetega Pavla (26.1.) če jasno nebo,Dobra bo letna, že stari pojo.",
            "Če Anton z dežjem prihaja, se zemlja še dolgo napaja.",
            "Če gredo na Neže dan žene na Kum bose, bodo kopice žita goste.",
            "Če bo prosinca mokrilo, bo pole in grozdje slabo rodilo.",
            "Če je na Pavla jasno nebo, dobra bo letina – stari pojo.",
            "Če je toplo v januarju, spomlad se pokvari.",
            "Če na Pavla sonce sije, gornik dosti vina vlije, trikrat žito dobro dozori in po volji kmetu se godi.",
            "Če na Tri kralje jasen dan bo, za dolgo zimo hrani seno.",
            "Če na Vincenca sonce peče, obilo vina v sode steče.",
            "Če na Pavla dan je čist in jasen, bo zemlje sad v tem letu krasen.",
            "Če Pavel nebo razjasni, letina dobra gotovo sledi.",
            "Če Pavel po kopnem prihaja, Jurij po snegu prihaja.",
            "Če prosinca grmi, slabo vreme preti.",
            "Če prosinca ni snega, ga mali traven da. V prosincu toplota, svečana mrzlota.",
            "Če prosinec ne zmrzuje, ne sneži, rad sušec to nadomesti.",
            "Če prosinca zelo lisica laja, še huda zima nastaja.",
            "Če se na Vincenca sonce le toliko pokaže, da bi mogel konja osedlati, dobra napoved za vino ne laže.",
            "Če na Tri kralje jamice polne vode, bomo imeli jeseni polne sode.",
            "Če vidiš prosinca komarje igrati, je treba s senom varčno ravnati.",
            "Če Vinka sonce peče, v sode vino teče.",
            "Če Vincenca sonce peče, po grlu vince gladko teče, tako dobro vince dozori, da motne dela ti oči.",
            "Če Vincenc ima sončno vreme, dobro je za žito in vinske gore.",
            "Če v januarju drevje od mraza poka, jeseni s sadjem preobloženo stoka.",
            "Fabijan in Boštjan, sok v drevju pognan.",
            "Jasni dnevi prosinca so veselje vinogradnika.",
            "Kadar na spreobrnjenje Pavla sneži in deži, letina slaba in huda preti.",
            "Kadar prosinec odpira dežnike, žetve poletne ne bodo velike.",
            "Kakor okrog Vincenca bo, tako čez leto ostalo bo.",
            "Kakršno bo vreme prvi dan, tak bo veliki srpan.",
            "Kakršno je na Makarija vreme bilo, takšno v kimovcu bo.",
            "Kakršno je vreme na Pavla stola dan, tako bo ostalo mesec dan.",
            "Kar boš delal na novga leta dan, to boš delal cel let in dan.",
            "Koliko dni pred Petrovim stolom grmi, toliko po njem mrazi.",
            "Lepo in jasno Pavla spreobrnjenje je rodovitnega leta znamenje.",
            "Makarij jasen in meglen naznanja prav tako jesen.",
            "Malo vode prosinca da obilo vinca, prosinec često naznanja v vodi, da bo malo v sodi.",
            "Na dan Neže se kuram rit odveže.",
            "Prosinca gorkota, v jeseni sirota.",
            "Prosinec mili, Bogu se usmili.",
            "Prvega prosinca in zadnjega sušca je zima najhujša.",
            "Sonce na Pavla stola dan obilo žita in vina da, če pa sneži, žito se podraži.",
            "V januarju toplo, v februarju hladno.",
            "V prosincu je bolje videti v hlevu volka, kakor brez suknje na polju moža.",
            "V prosincu zelena ledina, slabo se bo redila živina.",
            "Vredno novo leto da nam dobro žetvo.",
            "Če je Svečana pretoplo,bomo Malega travna radi za pečjo.",
            "Če je svečnica zelena,velika noč bo zasnežena.",
            "Če je svečnica preveč moče dobila,bo zemlja med letom malo pila.",
            "Svečanski Valentin (14.2.)prinese ključ od korenin.",
            "Sveti Matija (24.2.) led razbija,al' če ga ni, ga pa naredi.",
            "Kar Svečana ozeleni,se rado posuši.",
            "Ako je svečnica zelena, bo velika noč snežena.",
            "Ako je pretoplo svečana, bo malega travna počivala brana, ako pa je mraz, se poti obrazAko na svečnico burja vleče, bo dobro leto, ako pa jug, bo slabo.",
            "Bolje volka v hlevu imeti, kot se ob toplem soncu v svečnici greti.",
            "Če jazbec pred luknjo na soncu je zdaj, gre za štiri tedne rad nazaj.",
            "Če je februarja pretoplo, bomo v aprilu za pečjo.",
            "Če je na Blaževo oblačno, bo na Jurjevo privlačno.",
            "Če je svečnica preveč moče dobila, bo zemlja med letom malo pila.",
            "Če je svečnica topla in sončnega vremena, bodo čebele bogate in dobrega plemena.",
            "Če je svečnica topla, sneg prinaša, če je mrzla, ga pa odnaša.",
            "Če kaplja od sveče prej kot od strehe kane, huda zima še nori in kakih 27 dni ostane.",
            "Če na svečnico deži, se kmalu pomlad oglasi.",
            "Če na svečnico sneži, se že vigred oglasi.",
            "Če na svečnico sonce na jasnem vzhaja, lisica še v brlog zahaja.",
            "Če o svečnici burje ni, malega travna rada znori.",
            "Če o svečnici letajo mušice, nosimo še potem rokavice.",
            "Če se na svečnico jasno zdani, zima se raje še zadrži.",
            "Če svečana mačka na soncu leži, v sušcu spet rada na peč pribeži.",
            "Če sever konec svečana brije, nam dobre letine up zasije.",
            "Do svečnice mlaska, po svečnici praska.",
            "Jasen in sončen dan svečnice obeta dobro za lan.",
            "Kadar je na svečnico dež in Blaževo lepo, veliko v jeseni vina bo.",
            "Kadar je na svečnico jug, je še daleč plug.",
            "Kadar je svečnica jasna, obeta čebulnicam hasna.",
            "Kadar je svečnica oblačna, kmetica ne bo lačna.",
            "Kadar je svečnica zelena, je velika noč snežena.",
            "Kadar Matija zmrzuje, še 40 dni mraza prerokuje.",
            "Kakor na Petrovo vreme kane, tako ves mesec ostane.",
            "Kar svečana ozeleni, se rado posuši.",
            "Kolikor na svečnico škrjanec žvrgoli, toliko ga po svečnici slišati ni.",
            "Matija led razbija, če ga ni, ga pa naredi.",
            "Po 8. februarju gre sonce z gora v ravnine, novembra pa z ravnine v gore.",
            "Se Polona v soncu odtaja, v mokrem poletju gob preostaja.",
            "Valentin ima ključe od korenin.",
            "Igrajo v Sušcu se mušice,Malega travna vzemi rokavice.",
            "Če Sušca grmi,dobra letina sledi.",
            "Če ima o pustu sonce moč,mrzla bo velika noč.",
            "Če v Sušcu more kmet orati,Malega travna bo moral počivati.",
            "Če na štiridesetih mučencev  (10.3.) piha,bo pihalo štirideset dni.",
            "Če se na Jožefa (19.3.) vreme zvedri,prežene za letino kmetu skrbi.",
            "Če je Jožef (19.3.) lep in jasen,je dobre letine prerok glasen.",
            "Če na Gabrijelov dan (24.3.) zmrzuje,slana nič več ne škoduje.",
            "Brezen je desetkrat na dan jezen.",
            "Če breskve pred Gregorjem cveto, trije eno pojedo.",
            "Če Gabrijela zmrzuje, slana več ne škoduje.",
            "Če jagnjeta v sušcu na tratah nore, rada v aprilu v hlevu leže.",
            "Če je lepo na Jožefovo, veselo bo srce kmetovo.",
            "Če je na Jožefovo lepo, bo tudi koruza obrodila lepo.",
            "Če je na Ruperta jasno nebo, bo malega srpana ravno tako.",
            "Če je Šmarna v postu prav gorko, bo še prihodnjega leta toplo,Če je v sušcu zemlja preveč pila, bo poleti manj dobila.",
            "Če na 40 mučenikov dan zmrzuje, še 40 mrzlih noči prerokuje.",
            "Če ne prej, na Jedrt gorka sapica pihlja.",
            "Če se igrajo v sušcu mušice, v aprilu vzemi rokavice.",
            "Če se sušca da orati, bo treba aprila jokatiČe sušca dolgo sneg leži, to setev močno zamori.",
            "Če sušca grmi, dobra letina prihiti. Če sušca grmi, lakota beži.",
            "Če sušca prah okrog pometa, prav dobro letino obeta.",
            "Če vodi sušec na paše zelene, april jih nazaj v hleve požene.",
            "Dež pred velikim travnom tisto noč, pride dobra letina v pomoč.",
            "Jera prinese roso v košarici.",
            "Kadar je sušca še zeleno, redko leto je plemeno.",
            "Kadar slive marca in aprila cveto, ne obrodijo.",
            "Kadar sonce svete Jere obsije, čez tri dni sneg pokrije.",
            "Kar v breznu zraste, april pobrije.",
            "Kolikokrat je v sušcu slana, toliko dni stoji megla srpana.",
            "Kolikokrat sušca megla stoji, tolikokrat poleti ploha prigrmi.",
            "Kolikor sušca megle, toliko poleti dež gre.",
            "Na Gregorjevo najvišji gorjanec na drevo potrka.",
            "O Gregorju pravijo: Kmet dolgo njivo orje, klobuk postrani nosi, pa staro ženo kruha prosi.",
            "Po Gregorju od vsakega vetra sneg kopni.",
            "Sušec mišje luknje maši.",
            "Sušec jajce na kolu znese.",
            "Sušca goste megle plohe poletne rede. Sušca veliko megle dobro leto daje.",
            "Sušca prah obvelja kakor kepa zlata. Sušec pšenico po prahu valja.",
            "Sušca sneg je setvam kreg.",
            "Sušec preveč gorak, mali traven naopak.",
            "Sušec suši, mali traven deži, veliki hladi.",
            "Sušec vodo kali.",
            "Sveti Gregor je materi kožuh kupil.",
            "Če Malega travna sneži,siromaku zemljo gnoji.",
            "Če Malega travna rado grmi,slane se bati več ni.",
            "Mali traven deževen,kmet ne bo reven.",
            "Slana Malega travna je bolj nevarna,kot poleti toča in suša soparna.",
            "Če sončen je Mali traven in suh,bo Veliki traven za lepo vreme gluh.",
            "Če Jurij (24.4.) toplo vreme zakuri,širom pomladi odpre duri.",
            "Kolikor dni bodo žabe pred Jurijem (24.4.) regljale,toliko dni bodo po njem molčale.",
            "Aprilski dež mrtvo seje.",
            "Če češminje brhko cvete, rž rado bogato daje.",
            "Če je april deževen, kmet ne bo reven.",
            "Če je Jurija dež in na Petra suša, se raduje kmetova duša.",
            "Če je moker april, bo kmet veliko pridelkov dobil.",
            "Če je na Jurija lepo, vina dosti bo.",
            "Če malega travna grmi, slane se kmet več ne boji.",
            "Če malega travna toplo dežuje, rodovitno leto oznanjuje.",
            "Če na veliki petek dežuje, dobro se leto napoveduje.",
            "Če se aprila vreme smeje, se bo kisalo kasneje.",
            "Če se o Jurjevem krokar lahko v žitu skrije, mlatič jeseni dosti cepcev razbije.",
            "Če sušca sneg kazi, malega travna sneg gnoji.",
            "Jurij kaže duri. Jurij zakuri in odpre nam duri. Jurij podkuri.",
            "Jurij še pred mlajem da malo sena.",
            "Kadar je o maju Jurij, ni krme skozi duri.",
            "Kadar murva brsti, slane se več bati ni.",
            "Kolikor dni so žabe pred Jurijem ali Markom regljale, toliko dni bodo potem molčale.",
            "Na Jurja dan je pravi čas, da nam rž pokaže prvi klas.",
            "Slana v aprilu je bolj nevarna kot poletna toča in suša soparna.",
            "Sončen je april in suh, bo maj za lepo vreme gluh.",
            "Več ko ima leto dni, se v aprilu vreme spremeni.",
            "V dežju drevo cvete, sadja ne daje.",
            "Za april velja, da je še vedno veter bril.",
            "Za prvi in zadnji april nas bi vsakdo rad nabril.",
            "Če je Velikega travna lepo,je dobro za kruh in seno.",
            "Če je Velikega travna dosti dežja,bo jeseni tudi dosti blaga.",
            "Velikega travna mora biti tri dni mrzlo,če ni na začetku, bo na koncu tako.",
            "Veliki traven moker, Rožnik pa mlačen,kmet bo to leto žejen in lačen.",
            "Če se Pankracij (12.5.) na soncu peče,obilo mošta v sod priteče.",
            "Če Zofija (15.5.) zemljo poškropi,Vreme poleti prida ni.",
            "Če na Urbana (25.5.) sonce sije,Jeseni polne sode nalije.",
            "Ako prvega maja dan dežuje, dobro letino oznanjuje.",
            "Brez dežja Pankrac in Urban, up dobre trgatve je dan.",
            "Če je majnika lepo, je dobro za kruh in seno.",
            "Če je na Urbana lepo, rado suši se poleti seno.",
            "Če je pred Servacem poletje, mraz rad pritiska na cvetje.",
            "Če maj se z vročino začenja, mraz še po Urbanu rad ne jenja.",
            "Če na Urbana sonce sije, jesen polne sode nalije.",
            "Če Pankraca sonce peče, sladko vince v klet poteče.",
            "Če se Urbanu sonce zahoče, bo tudi poletje suho in vroče.",
            "Če Urban greje zelo, trgatev dobra bo.",
            "Če Urban suši in Vid mokri, bo prav za žejne ljudi.",
            "Če Zofija zemlje ne poškropi, vreme poleti prida ni.",
            "Dež ob vnebovhodu za košnjo ni pogodu.",
            "Filip napija, Zofija popija.",
            "Hladen majnik ti gotovo da slame dosti in tudi sena.",
            "Kadar pride mesec maj, vpraša, če je še v kašči kaj.",
            "Kakor je vreme Urbana, tako bo tudi malga srpana.",
            "Kdor nima ob Filipu in Jakobu še voza sena, naj se gospodar preobrne.",
            "Kocjan gobe seje in v zemljo da, Primož pa pobrana.",
            "Maja mora biti tri dni mrzlo, če ni na začetku, je ob koncu tako.",
            "Majnika dosti dežja, obeta jeseni dosti vsega.",
            "Na Urbana sonce gorko, obilno vina, ki bo sladko, če pa ta dan prirosi, trta le cviček rodi.",
            "O Urbanu se mora trta videti s hriba v hrib.",
            "Po svetmu Servati ni mraza se bati.",
            "Saditi fižol na Florjana, je dovolj zarana.",
            "Slana v začetku maja zoritvi sadja jako nagaja.",
            "Sveti Pankracij, Servacij in Bonifacij so ledeni možje, če prej ni slane bilo, tudi pozneje ne bo mrzlo.",
            "Urban glive v zemljo meče, Primož jih pa povleče.",
            "Urban jasen, jeseni hasen.",
            "Velikega travna če pogosto grmi, se kmet dobre letine veseli.",
            "Velikega travna mokrota, malega srpana suhota.",
            "Veliki traven moker, rožnik pa mlačen, kmet bo to leto žejen in lačen.",
            "Rožnika toliko dežuje,da zadnji koreninici zadostuje.",
            "Rožnik deževen – viničar reven.",
            "Če Rožnika sonce pripeka in vmes dež rosi,ni treba se bati teka; obilno zemlja rodi.",
            "Če Barbara (11.6.) deži,Bodo jeseni grozdja polne kadi.",
            "Vid, dežja ne daj,da bo žetve kaj!",
            "Če je megla na dan Vida,je pšenica malo prida.",
            "Do kresa (21.6.) suknjo oblači,po kresu jo pa s seboj vlači.",
            "O kresi (21.6.) je dan tako dolg,da človek, če se skrči, vanj trči,če se pa stegne, pa vanj dregne.",
            "Ako na Medarda dežuje, štirideset dni še naletuje.",
            "Ako na Medarda deži, se grozdje do brente kazi.",
            "Ako  na Medarda  je vreme lepo, najlenejši kosec pospravlja suho seno.",
            "Ako na Ivanje brli, po Ivanju kipi.",
            "Če Anton seje proso, gre Vid tretji dan  pogledat, če z njim kaj bo.",
            "Če Barbara deži, bodo jeseni grozdja polne kadi.",
            "Če je megla na Vida dan, je pšenica malo prida.",
            "Če junija sonce pripeka in vmes dežek rosi, ni treba se bati teka, obilno zemlja rodi.",
            "Če kres deži, orehov ni. Če na kresni dan dežuje, orehom slabo prerokuje.",
            "Če rožnika sonce pripeka, pohlevno deži, veliko obeta žita, strdi.",
            "Če rožnika toplo dežuje, kašče in uljnjake napoveduje.",
            "Če se Medard kislo drži, do konca meseca ni sončnih dni.",
            "Če trs pred Vidom ocvete, se dobrega vina nadejati smete.",
            "Če vinska trta ne cvete kersnika, ostane lesnika.",
            "Dež na Vida, ječmenu ne kaže kaj prida.",
            "Dež na Šentjanža, slabo letino nareja, sonce naj se raje pratiki smeje.",
            "Do kresa suknjo oblači, po kresu jo pa seboj vlači.",
            "Junija toliko dežuje, da zadnji koreninici zadostuje.",
            "Kadar na Ladislava dežuje, dež še dolgo kraljuje.",
            "Kakor vreme kresnic, tolko bo tudi žanjic.",
            "Kakor vreme na Medarda kane, tako ves mesec ostane.",
            "Kakor se Medarda zdani, vreme še štirideset dni trpi.",
            "Kakor vreme rožnika mini, taka se grudna ponovi.",
            "Kolikor dni kukavica še po kresu kuka, toliko tednov po Mihaelu v roke ne huka.",
            "Lepo vreme prvega dne, kmetje se letine vesele.",
            "O kresi se dan obesi. O kresi je dan tako dolg, da človek, če se skrči, vanj trči, če se pa stegne, vanj dregne.",
            "O kresu je tako dolg dan, da če bi zjutraj kravo vodil, ima zvečer tele.",
            "O kresu se mora vrabec že v prosu skriti.",
            "O Vidi se skozi nič ne vidi.",
            "Pred kresom prosi, naj deži, potem prositi treba ni.",
            "Pred Vidom napovedujejo muhe dneve prav suhe.",
            "Preveč dežja v rožnem cvetu ni nič kaj po volji kmetu.",
            "Rožnika mrzlo deževanje, slabo za vino in panje.",
            "Rožnik deževen, viničar reven.",
            "Sever, ki ta mesec vleče, obilo žita povleče.",
            "Svetga Vida meglica pride po vince in pšenico.",
            "Sveti Vid je češenj sit.",
            "Štirideset dni se nebo solzi, če na Medardovo iz njega rosi.",
            "Urbanovo sonce in Vidov dež, na dobro leto upati smeš.",
            "Vidove megle se žito boji, če Murčar jo vidi, o žetvi dvojiVnebovhod je tak praznik, da tič tiča ujame, da meso je, človek pa človeka navije, da vino pije.",
            "Če na drugi dan Malega srpana ne bo lepo,se dež ves mesec ustavil ne bo.",
            "Če Cirila in Metoda (7.7.) dež pere,orehe in kostanj z drevja obere.",
            "Če na Marjeto (20.7) dež lije,seno na travniku zgnije.",
            "Če Magdalena (22.7.) na dežju stoji,dolgo slabo poletje preti.",
            "Na nebu megla 25. dnehudo zimo napove.",
            "Če na Jakoba (25.7.) dežuje,ostro zimo oznanjuje.",
            "Ako 2. julija v dežju leto obiskuje, s hriba v tedne oznanjuje.",
            "Ako do Urha slišiš kukavico in Urh z Marjeto kače pase, posevek dobro rase.",
            "Ako je dež na Cirila in Metoda, oreh in kostanj domala ogloda.",
            "Ako je drugi dan malega srpana grdo, še štirideset dni bo mokro.",
            "Ako je drugi dan tega meseca lepo, štirideset dni bo tako.",
            "Ako je na Lovrenca in Antona lepo še jeseni tako.",
            "Ako je vreme še tako deseti dan, tako bo z malim še veliki srpan.",
            "Ako na Marjetin dan dežuje, orehov in lešnikov ni, seno pa se ne posuši.",
            "Ako na Magdaleno dežuje, se dež še rad obdrži.",
            "Če je Aleš suhoparen in suh, si napravi za zimo topel kožuh.",
            "Če je Jakob lep, bo božič mrzel, a obilna jesen, to je znano vsem ljudem.",
            "Jakobova ajda in Ožbaltova repa sta malokdaj lepa.",
            "Je tega meseca presuho, ostane grozdje drobno.",
            "Kakor vreme Jakoba dopoldne, tako bo tudi pred božičem te dni.",
            "Magdalena drobničarka, Ana pogačarkaMarjeta grom in strelo obeta.",
            "Mrzel in moker mali srpan, trtnemu sadu je močno v bran.",
            "Na nebu megla 25.dne, hudo zimo napove.",
            "O Jakobu pšenica zori ali zgori, grozdje pa na božjo pot odide in šele ob Jerneju nazaj pride.",
            "Pasji dnevi mrzli in deževni so za vincarja revni.",
            "Pred Jakobom tri dni lepo, rž v redu dozorela bo.",
            "Česar Veliki srpan ne skuha,tudi Kimavec ne prekuha.",
            "Če se megla zjutraj v zrak vzdiguje,slabo vreme napoveduje;če pa zemlja meglo posrka,lepo vreme na vrata trka.",
            "Če bo o Porcijunkuli (2.8.) vročina,huda bo prihodnja zima.",
            "Vreme, ki ga Lovrenc (10.8.) naredi,do konca jeseni drži.",
            "Veliki šmaren (15.8.) brez dežja,sladko vince bo doma.",
            "Če Jerneja  (24.8.) veter zjasni,lepo vreme še dolgo trpi.",
            "Če Lovrenc jasen, bo grozd strden in vincar glasen.",
            "Če je na Lovrenca lepo, tudi jeseni ne bo grdo.",
            "Če se avgusta po gorah kadi, kupi si kožuh za zimske noči.",
            "Če se megla zjutraj vzdiguje, slabo vreme napoveduje.",
            "Če srpana veter zvedri, vreme še dolgo trpi.",
            "Če vika maša mokri, mala maša praši.",
            "Če velikega Šmarna sonce peče, dobro vince v sod poteče.",
            "Kakor Jernej in zadnji srpan vremeni, se vsa jesen drži.",
            "Lovrenc deževen nam vino sladi in ajda moč po njem dobi.",
            "O Lovrencu mora biti pletev končana.",
            "Orehe piškave stori rad dež na Janeza glave.",
            "Po vremenu Jerneja se vsa jesen nareja.",
            "Rok išče otrok.",
            "Slana na Jerneja, gotovo bo zijala vrana.",
            "Sonce srpana grozdje meči, z medom navdana ajda diši.",
            "Srpana če veter zvedri, vreme še dolgo trpi.",
            "Strd za potice popijejo Jerneja meglice.",
            "Veliki srpan kar ne skuha, tudi kimavec ne prekuha.",
            "Veliki šmaren brez dežja, sladko vince bo doma.",
            "Vreme, ki ga Lovrenc naredi, celo se jesen drži.",
            "Zrel grozd Jerneja dobiti, dosti bo sladkega mošta.",
            "Če se zgodaj selijo ptiči,bo huda zima ob božiči.",
            "Tilen  (1.9.) oblačen, meglen,grda, deževna jesen.",
            "Če o Mihaelu  (29.9.) sneg naletuje,dolga se zima obljubuje.",
            "Ako je na Ilja jasno gorko, bo štiri tedne vedro.",
            "Til oblačen, meglen, grda, deževna jesen.",
            "Ako je Matevž vedren, bo prijetna jesen.",
            "Ako na Mateja sonce sije, kmalu lepa jesen zasije.",
            "Ako je Mavricija jasno nebo, vetrovi po zimi hudo brijejo.",
            "Ako Mavricija sonce zasije, pozimi huda sapa brijeČe Mihael v želodu leži, obilno s snegom božič gnoji.",
            "Če na Mihalevo sever vleče, veliko zimo in sneg obleče.",
            "Če o Mihaelu žerjavi še ne gredo, pred božičem zime k nam ne bo.",
            "Če pred Mihaelom jasna noč, bo tudi zima imela veliko moč.",
            "Do Mihaela na soncu, potem se na peči otava suši.",
            "Kadar prve dni kimovca pogostoma grmi, bo dosti tepkovca, pšenice, rži.",
            "Kakršen kimavec, takšen bo sušec.",
            "Kakršno bo vreme na Ilija kazalo, bo ves mesec ostalo.",
            "Kakršno vreme na malo mašo nastane, rado še dva meseca ostane.",
            "Kakršno vreme o kimavca mlaji, takšno je vso jesen najrajši.",
            "Kakršno vreme na malo mašo kane, tako trideset dni rado ostane.",
            "Kdor po mali maši kosi, ta za pečjo suši.",
            "Miha podpiha.",
            "Miha kašo piha.",
            "Mihaela če grmi, viharjev veliko pozimi buči.",
            "O Mihaelu rad žene hudič polhe.",
            "Slana pred Mihaelom če pada, tolikokrat ob letu o trjakih je rada.",
            "Šišk veliko Mihael da, zgodnja bo zima in veliko snega.",
            "Več boš o Miholji nakosil, kot o pustu naprosil.",
            "Zagledati na nebu šmarni križ, pomeni smrt tisto leto.",
            "Žerjavi ko lete na tuje, brž se zima približuje.",
            "Če je Vinotoka mraz in burja brije,Prosinca in Svečana sonce sije.",
            "Če listje hitro odleti,vsak naj zime se boji.",
            "Če se drevje zgodaj obleti,polje ob letu dobro rodi.",
            "Vlažen, mrzel Luka (18.10)kmalu sneg prikuka.",
            "Kakor je Uršula (21.10) začela,se zima bo izpela.",
            "Če je na Uršulo lepo,čez tri dni deževalo bo.",
            "Če je Gal  suhoparen, oznanjuje, da ob letu suša pripotuje.",
            "Če je na Uršule lepo, še lene babe nastil dobe.",
            "Če je vlažen in mrzel Luka, repo popuka in osmuka.",
            "Če na Urše dan kmet zelje pospravi, mu ga vreme Simona in Jude v nič ne pripravi.",
            "Če vinotoka mraz in burja brije, prosinca in svečana sonce sije.",
            "Kakor Uršule dan je, bode tudi pozimi stanje.",
            "Kakor je Urša pričela, bo zima vsa izpela.",
            "Kakršno vreme Urša prinese, tako se rada jesen in zima obnese.",
            "Luka pravi Urši: pospravi repo, sicer ti jo bom s snegom zabelil.",
            "Lukež, repni pukež.",
            "Oktober je dober.",
            "Simon in Juda se s snegom prebudita.",
            "Urša v kad repo buša.",
            "Vinotoka če zmrzuje, pa prosinca odjenjuje.",
            "V oktobru burja, mraz, januarja sončen čas.",
            "Vinotoka deževanje, grudna vetrov divjanje.",
            "Vinotoka veliko vode, grudna hudi vetrovi buče.",
            "Vreme vinotoka je  aprilu za poroka.",
            "Če na mrtvih dan dežuje,se huda zima pričakuje.",
            "Če mokro zemljo sneg pokrije,bo malo prida za kmetije.",
            "Sonce na Martina (11.11.),pred vrati huda zima.",
            "Kadar Martin (11.11.) oblake preganja,nestanovitna se zima oznanja.",
            "Če na Cecilijo grmi in treska,bo ob letu žita kot peska.",
            "Katarina (25.11.) nam ne laže,po sebi Prosinca vreme kaže.",
            "Ako na mrtvih dan dežuje, zamete zima pričakuje.",
            "Ako na mrtvih dan deži, vreme po snegu diši.",
            "Ako je na Vseh svetnikov dan lepo vreme, bo prihodnje leto veliko žira.",
            "Ako je na Lenartovo lepo ali grdo, do božiča bo ostalo tako.",
            "Ako je na Martinje lepo, bo za tri dni grdo.",
            "Cecilije grmenje, dobre letine znamenje.",
            "Če za Martina sonce sije, huda zima bo.",
            "Če se Martinova gos po ledu plazi, o božiču navadno po blatu gazi.",
            "Če pred Martinom zmrzuje, je pred božičem povodenj.",
            "Če pred Martinom zmrzuje, prihodnje leto češenj ni.",
            "Če Martin oblake preganja, nestanovitno zimo napravlja.",
            "Če je za Martina dež, je potem zmrzlina, pozebe ozimina in je tu draginja.",
            "Če je Martin oblačen ali meglen, pride zima voljna kot jesen.",
            "Če se o Martinu vinska buča z zelenim trtnim perjem zamaši,Če Cecilija hudo grmi, dosti pridelka ob letu kmet dobi.",
            "Do vseh svetih grdo, po vseh svetih lepo.",
            "Elizabeta na belem konju prijezdi.",
            "Klemen zaklene, Katarina grušta, Andrej vse s snegom pokrije.",
            "Kakršen Konrada dan, takšen bo malone ves svečan.",
            "Kakršno vreme je na Ivana dan, tako pozimi, posebno svečana.",
            "Katarina ali kres, če je mrzlo, neti les.",
            "Katarine dan ne laže, če po sebi prosincu vreme kaže.",
            "Ko pride svet Martin je paše konc.",
            "Kolikor ima Lenart snega na planini, toliko ga ima božič v dolini.",
            "Lenart zemljo zaklene.",
            "Listopada gredo duše v nebo, kakor čebele iz panjev.",
            "Listopada zmrzlina, je svečana ne bo.",
            "Listopada južnina, svečana mrzlo.",
            "Martin naj bo suh, da pozimi raste kruh.",
            "Mraz na Vse svete pomeni lep Martinov dan.",
            "Na Andreja sneg, z žitom kreg.",
            "Pozimi hudi zameti, če so deževni vsi sveti.",
            "Vseh svetnikov mraz, o Martinju topel čas.",
            "Vsi svetniki radi prineso kak dan še vreme lepo.",
            "Za Martina če je jasno, bo v treh dneh sneg, če oblačno, sneži še na ta dan.",
            "Za soncem Martina pride takoj sneg, zmrzlina, pa čeprav ta dan greje, tri dni se babje leto šteje.",
            "Za svetga Andreja je sneg železen.",
            "Za sveto Elizabeto greš v mest na vozu, iz mesta pa že na saneh.",
            "Za sveto Katarino če dežuje, tedaj bo vlažna zima, če pa je takrat sneg, bo snežena.",
            "Če Grudna bliska, grmi,za drugo leto vetrove budi.",
            "Grudna mraz in sneg,žita dosti prek in prek.",
            "Na Barbaro (4.12.) mraz,bo trajal ves zimski čas.",
            "O božiču zeleno,o veliki noči sneženo.",
            "Božični dež vzame rž.",
            "Če vidiš rimsko cesto na sveto noč sijati,se je dobre letine nadejati.",
            "Če Štefana (26.12.) burja prinese,vinogradniku pridelek odnese.",
            "Tepežni dan (28.12.) oblačen,ne boš ob letu kruha lačen.",
            "Ako se grudna bliska in grmi, drugo leto dosti vetrov.",
            "Ako prvega dne v adventu na Barbaro je mraz, trajal bo ves zimski čas.",
            "Ako se vidi na Barbare dan na njivi strnišče, se bo videlo potem vsak mesec.",
            "Ako se zmrzlina grudna ne otaja, še prosinca hujši mraz postaja.",
            "Božični veter vzame rž.",
            "Če na božič dežuje, prihodnje leto močo oznanjuje.",
            "Dež in veter pred božiček, koplje jamo rad mrličem.",
            "Dež na Štefanje obeta le malo žita drugo leto.",
            "Dnevi od Lucije do božičnega dne ( 13.12.- 25.12.) vreme vseh mesecev za drugo leto povedo.",
            "Grom in blisk o zimskih kvatrih, huda zima bo pri vratih.",
            "Grudna suh veter piska, poleti po suhi pomladi nato suša pritiska.",
            "Grudna mraz in sneg, žita dosti vse povprek.",
            "Jasno in svetlo na sveti večer, dobre letine je dost, če pa je oblačno in temno, žita ne bo.",
            "Kadar v adventu jug hladi, drugo leto dosti sadja rodi.",
            "Kakršen adventni most, takšen post.",
            "Kakršno vreme na božični dan, tako bo še leto dan.",
            "Kolikor bliže božič mlaja, toliko hujši mraz prihaja.",
            "Kolikor ivja se o božič na vejah blesti, toliko sadja prihodnje leto zori.",
            "Lucija krajša dan.",
            "O božiču zeleno, o veliki noči sneženo.",
            "O božiču se spodobi malo snega in belega kruha.",
            "O božiču zunaj na soncu, o veliki noči za pečjo.",
            "Od božiča do Treh kraljev če gosta megla nastaja, bo veliko bolezni doma.",
            "Po božiču gre dan gori, sneg doli.",
            "Polna luna blizu božiča južno zimo nam da.",
            "Prvi teden huda zima, osem tednov ne odkima.",
            "Sapa ki na sveti večer piha, vse prihodnje leto ne odpiha.",
            "Slaba bo letina, revščine vir, če mokrota moti božični večer.",
            "Svetal božič bo dal jeseni poln kozarec.",
            "Sveti dan vetrovno, ob letu bo sadja polno.",
            "Sveti Tomaž sedi vsak mož doma.",
            "Svetle božične noči z žitom temne, temne božične noči pa svetle.",
            "Tepežki dan 28.12. oblačen, k letu ne boš lačen.",
            "Zelen božič, bela velika noč.",
            "Ena lastovka še ne prinese pomladi.",
            "Da se bliža pomlad,slutijo rože prej kakor človek.",
            "Vsak zvon ne odžene toče.",
            "Bo lepo vreme?Bo, da bo vrana zijala,ko bo oreh ukrala.",
            "En cvet še ne naredi pomladi.",
            "Mnogo snega, mnogo sena.",
            "Če jeseni ni kam devati,spomladi ni kje jemati.",
            "Ne prodaj kože, dokler medved v brlogu spi.",
            "Ako zgodaj listje pade,so rodovitne njive rade.",
            "Lepega vremena in sitega trebuhase človek naveliča.",
            "Pred lepim vremenom so živali živahne,so marljive in navzgor silijo.",
            "Če se polž globoko zakoplje,se huda zima prikoplje.",
            "Kdor neprestano opazuje oblake,ne bo nikoli žel.",
            "Bodi zima, bodi kres,kadar zebe, neti les.",
            "Rdeča zora – mokra gora.",
            "Vsak dež ima svoj čas.",
            "Zima rada z repom bije,če dolgo toplo sonce sije.",
            "Ob nevihti se hrasta, smreke in vrbe boj,pa raje pod bukvijo in lipo postoj.",
            "Zavaruj se vedrega juga in oblačne burje.",
            "Če pomladi trta ne joče,tudi jeseni preša ne stoče.",
            "Ujmi ne uideš;suša požre en hleb kruha,moča pa dva.",
            "Hude nevihte ne trajajo dolgo.",
            "Prava sreča se le enkrat ponuja.",
            "Srečen je kdor zna živeti z majhnimi željami.",
            "Sreča je opoteča.",
            "Srečen si, ko verjameš v srečo.",
            "Srečen si, če si ne želiš,česar ne moreš imeti.",
            "Sreča človeka sreča, ujeti se ne da.",
            "Srečnejši je tisti, ki daje,kakor oni, ki jemlje.",
            "Ni srečen, kdor veliko ima;srečen je, kdor malo potrebuje.",
            "Sreča lahko da mnogim preveč,zadosti nikomur.",
            "Prej boš srečo srečal, če ji greš naproti,kakor da čakaš nanjo.",
            "Niso vsi srečni, ki imajo srečo.",
            "Sreča je svobodna ptica;kjer se ji zdi, tam posedi.",
            "Sreča hodi za hrbtom;primi jo, ko te pogleda čez ramo.",
            "Sreča je opoteča; k enim prihaja,ko od drugih odhaja.",
            "Sreča na razpotju sedi.",
            "Čemu strmiš v daljavo,ko pa sreča ob tebi stoji.",
            "Kdor hitro se znajde,sreča ga najde.",
            "Sreča se utrudi,če koga nosi dolgo na ramah.",
            "Če bi bila sreča res slepa,bi se dala večkrat ujeti.",
            "Ne išči sreče v oblakih;skloni se in jo poberi!",
            "Kdor čaka in v upih živi,prerada nazadnje mu sreča zaspi.",
            "Če v svoji sreči visoko prilezeš,lahko tudi globoko padeš.",
            "Komur se sreča jahati pusti,ga nese, kamor ona želi.",
            "Ne prevzemi se v sreči,ne ponižuj se v nesreči!",
            "Sreča ni slepa, ampak celo oslepi tiste,ki jih je objela.",
            "Srečnejše živi,kdor o svoji sreči molči.",
            "Če srečen si, ne pravi svetu, ker je nevoščljiv;če nesrečen si, ne toži svetu, ker je neobčutljiv.",
            "Sreča in pamet se redko srečata.",
            "Kdor srečo uživati želi,je ne razglasi.",
            "Sreče in mavrice ne vidimo nad svojo streho.",
            "Srečo lažje najdeš kot obdržiš.",
            "Preveč sreče je lahko vzrok za strah.",
            "Sreča ljudi prej zlomi kot nesreča.",
            "Sreča oči zapira, nesreča jih odpira.",
            "Sreča je prava potepenka;nikoli ne ostane pri enem samem človeku.",
            "Sreča je kakor sonce;ko je najlepša, zatone.",
            "Srečo ovira pričakovanje velike sreče.",
            "Sreča je kakor čaša;bolj je svetla, bolj je krhka.",
            "Sreče ne spoznaš z glavo, ampak s srcem.",
            "Človek ni nikoli tako srečen, kot misli,niti tako srečen, kot je upal, da bo.",
            "Padla mu je sekira v med.",
            "Veliko srečo spremlja zavist.",
            "Sreča pridobi prijatelje,nesreča jih preizkuša.",
            "Vsak je svoje sreče kovač.",
            "Sreče se ne da kupiti;blaginja ni pogoj za srečo.",
            "Za srečo ni tablet.",
            "Nova vreča, nova sreča.",
            "Če želiš uspeti, moraš imeti srečo,da dobiš priložnost;da priložnost znaš izkoristiti,pa potrebuješ pamet.",
            "Išči novo srečo, a stare ne zavrži!",
            "Kdor ima pamet, ne potrebuje sreče.",
            "Nimam in nimam sreče;še če bi padel na hrbet, bi si razbil nos.",
            "Eni srečo imajo, pa niso srečni;drugi jo iščejo, pa je ne najdejo.",
            "Tik sreče nesreča preži.",
            "Srečne oči, ki jo vidijo (štiriperesno deteljico),nesrečna roka, ki jo utrga.",
            "Sreča na račun drugih je tatvina.",
            "Ko citre najlepše pojejo, poči struna.",
            "Sreča pamet vzame, nesreča jo pa vrne.",
            "K srečnemu še tuji prihajajo,pred nesrečnimi pa še domači uhajajo.",
            "Srečen človek je rad pozabljiv.",
            "Človeku, ki ne upa več,srce utripa vedno bolj počasi.",
            "Ko si zelo srečen, še sam sebe ne spoznaš;ko si nesrečen, te nihče noče poznati.",
            "Dokler bo šla sreča s teboj,boš imel prijateljev cel roj.",
            "Če pričakuješ, da boš srečen,lahko postaneš zelo nesrečen.",
            "Sreča in bogastvo sta dva različna škornja.",
            "Že to je sreča, da ti prizanaša nesreča.",
            "Ko se nesreča pomiri, se sreča oglasi.",
            "Samo veseli ljudje najdejo srečo.",
            "Dokler nisi bil nesrečen,ne veš kaj je sreča.",
            "Dolgočasje je bolezen,ki grozi srečnemu človeku.",
            "Za srečo sta potrebna dva.",
            "Zadovoljstvo srca srečo ti da.",
            "Srečnemu še petelin znese jajca.",
            "V pesek vpiši grenke ure svoje,a v kamen ukleši, kar zvonček sreče poje.",
            "Zamujena sreča je dvojna nesreča.",
            "Živimo, da iščemo srečoin ne zato, da bi jo našli.",
            "Tista ki je našla prstan,je bila srečna toliko časa kakor tista nesrečna,ki ga je izgubila.",
            "Najsrečnejše ljudi poštenje stori.",
            "Kdor se nad starši jezi,tega sreča samo duši.",
            "Vse veselje hitro mine,vsaka sreča hitro zgine.",
            "Sreča je zaveznica pogumnih.",
            "Komur sreča ni namenjena,ta si zastonj pete za njo brusi.",
            "Življenje traja do smrti.",
            "Življenje je kot basen;ni važno, kako je dolga,ampak kakšen je nauk.",
            "Življenje je kot blisk;oba hitro mineta.",
            "Življenje je dober učitelj,ki si zasluži tudi dobro plačilo.",
            "Življenje je večen kompromis.",
            "Življenje je potovanje v negotovost.",
            "Pogum življenje krajša,previdnost ga pa daljša.",
            "Vsako življenje piše svoj roman;samo tiska ga nihče.",
            "V vsakem življenju pade nekaj dežja.",
            "Poznamo začetek, poznamo konec,sredina pa je neznanka.",
            "Kdor v jezi in žalosti molči,nikdar dolgo ne živi.",
            "V življenju ni ravnih poti.",
            "Če ljubiš življenje, ne zapravljaj časa;čas je snov iz katere je življenje.",
            "Dobra volja pol življenja hrani.",
            "Na svet prideš z jokom, odideš s stokom.",
            "Tudi dolgo življenje ima svoj konec.",
            "Ko bi ljudje ne mrli, bi svet podrli.",
            "Kdor dolgo kašlja, dolgo živi.",
            "Bogati umrje, reveža pa bog vzame.",
            "Preden se zavemo, kaj sploh življenje je,ga je že pol mimo.",
            "Nič ni hudega, če verjameš v sanje,samo zato ne prespi vse življenjske dni.",
            "Dolgost življenja našega je kratka.",
            "Človeška pomlad pride le enkrat.",
            "Če živiš s spomini, ostariš,če z načrti, se pomladiš.",
            "Mlad more, star mora umreti.",
            "Mladost mine, ko cvet izgine.",
            "Leta hitijo, dnevi se pa vlečejo.",
            "Samo živali rade umirajo v samoti.",
            "Boljše je umreti kakor umirati.",
            "Živeti moraš tako, kot moreš,če ne moreš, kakor hočeš.",
            "Kar si vse življenje sadil,to boš na pozna leta užil.",
            "Življenje je dolgočasno, če v njem ni boja.",
            "Življenje ni praznik, je delovni dan.",
            "Življenje je cvet,ljudje v njem so med.",
            "Življenje je kratko za tiste,ki ga merijo z užitki.",
            "V življenju popravljaj majhne okvare,da ne postanejo velike.",
            "Delaj kakor bi večno živel,misli, kakor da boš jutri umrl!",
            "Brez iluzij, bi življenje ugasnilo od dolgočasja.",
            "Dobro živeti in srečno umreti –to pomeni hudiču račun podreti.",
            "Kot ne more drevo živeti brez korenin,ne more človek živeti brez družbe.",
            "Dokler živiš – živi!",
            "Kaplja se izlije v morje in živi dalje.",
            "Življenje je cvet,ljubezen v njem je med.",
            "Življenje se meri po delih,ne po dnevih.",
            "Minljiv si, le tvoja dela so tvoj spomin.",
            "Repa, korenje, dolgo življenje.",
            "V prvi polovici življenja človek kvari zdravje,v drugi polovici ga pa popravlja.",
            "Življenje brez ljubezni je kakor leto brez pomladi.",
            "Če želiš veliko let šteti,moraš od malega zmerno živeti.",
            "Vsak čas v življenju nosi svoj obraz.",
            "Življenje zajemaj s polno žlico.",
            "Ljubezen je večna, dokler traja.",
            "Ljubezen, ki mine, ni bila nikoli prava ljubezen.",
            "Ljubezen je sreča brez miru.",
            "Ljubezen je kot rosa;pade tako na vrtnico kakor na koprivo.",
            "Ljubezen je kot ogenj;večja je, bolj se kadi.",
            "Ljubezen je kot solza;rodi se v očeh, pade pa v srce.",
            "Ljubezen je kot morje;nevarno, če ne znaš plavati.",
            "Ljubezen je kot zahajajoče sonce;ko je najlepše, zaide.",
            "Ljubezen je kot bolezen,ki je nočemo zdraviti.",
            "Ljubezen je kot kobilica;skače z jezika v srce.",
            "Ljubezen je kot mesec;ko raste, že usiha.",
            "Ljubezen je kot oreh;kdor ga ne stre, ga ne more užiti.",
            "Ljubezen je kot sneg;ko se stopi, se spremeni v blato.",
            "Ljubezen se ne da na nitko ujeti,a niti s palico pregnati.",
            "Ljubezen rodi ljubezen.",
            "Ljubezen sliši raje sladko laž,kakor bridko resnico.",
            "Ljubezen se rodi iz zaupanja,živi od upanja, umre od usmiljenja.",
            "Ljubezen se pri moškemu začne v očeh,pri ženski v ušesu.",
            "Ljubezen je najsrečnejša pot k nesreči.",
            "Ljubezen ima četvero oči,pa je vseeno slepa.",
            "Ljubezen je slepa,a vidi na daljavo.",
            "Ljubezen se opazi kot luknja v nogavicah.",
            "Ljubezni in rdečega nosu ne moreš skriti.",
            "Ko ljubezen govori, razum molči.",
            "Ljubezen je trpljenje,življenje brez ljubezni pa je pekel.",
            "Prvi dih ljubezni je poslednji dih modrosti.",
            "Govor ljubezni je v očeh.",
            "Oči so prvi sel ljubezni.",
            "Oči iščejo kar je srcu všeč.",
            "Vsake oči imajo svojega malarja.",
            "Česar ljubezen ne vidi, verjame.",
            "Česar je polno srce, rado iz ust gre.",
            "Kar od srca pride, se srca prime.",
            "V ljubezni oprostiš, a ne pozabiš.",
            "Ljubezen brez poljubov je kot kruh brez soli.",
            "Z ljubeznijo mine čas,s časom ljubezen.",
            "Kjer je veliko ljubezni,je malo besed.",
            "Ko človek ve, zakaj ljubi, ne ljubi.",
            "Čar prve ljubezni je v tem, da ne vemo,kdaj se bo končala.",
            "Molk je pogovor med zaljubljenci.",
            "Rajši srce brez besed kot besede brez srca.",
            "Kratka ljubezen, dolgi vzdihi.",
            "Začetek je sladak, konec grenak.",
            "Kdor trpi zaradi ljubezni,ne občuti bolečine.",
            "Ko je ljubezenski ogenj dogorel,ga je težko spet zanetiti.",
            "Ko se ljubezen ohlaja, ljubosumje prihaja.",
            "Ko ni več ljubezni, ni več zaupanja.",
            "Dolga ljubezen redko na hitro umre.",
            "V ljubezni je beg edina zmaga.",
            "Ljubezen je z medom namazan križ;med se poliže, križ ostane.",
            "Človek brez ljubezni jemlje,poln ljubezni daje.",
            "V lažni ljubezni je več pelina,kot je lahko v pravi ljubezni medu.",
            "Prepir zaljubljencev je obnavljanje ljubezni.",
            "Ljubezen zadušena še ni pogašena.",
            "Stara ljubezen ne zarjavi;če ne gori, pa tli.",
            "Ko v ljubezni začutiš verige, se poslovi.",
            "Nova ljubezen pride in gre,stara se obdrži.",
            "Stara ljubezen se spet ponovi;na starem ognjišču se najraje greje.",
            "Stara ljubezen in star les se rada vnameta.",
            "Dolga ljubezen, gotova bolezen.",
            "Stara ljubezen ne izgubi korenin.",
            "Nova ljubezen preizkuša prejšnjo.",
            "Nobena ljubezen ni tako vroča,da bi je zakon ne ohladil.",
            "Čisto ljubezen je treba osvajati,ničvredna se sama ponuja.",
            "Pametna ženska zna odkloniti poljub tako,da ne ostane brez njega.",
            "Ljubimec je ljubosumen na ljubimca,ne na moža.",
            "V ljubezni zna ženska vse, česar se ni naučila.",
            "Moškega osreči več stvari,žensko samo ljubezen.",
            "Če želiš biti ljubljen – ljubi.",
            "V ljubezni so samo začetki privlačni,zato ljudje začenjajo vedno znova.",
            "Prehitra ženitev, gotova streznitev.",
            "Najprej štalca, potem pa kravca.",
            "Ne kvari vina z vodo,kakor ne ljubezni s poroko.",
            "Moža je lažje dobiti kot obdržati.",
            "Dolga zaroka, mala poroka.",
            "Kdor sne ljubezen pred poroko,mu je za zakon ne ostane nič.",
            "Ljubezen je slepa na eno oko,samoljubje pa na obe očesi.",
            "Ljubezen ne modruje;če pa modruje, to ni ljubezen.",
            "Šolska ljubezen na pesek se piše,veter zapiha in vse izbriše.",
            "Nasprotje ljubezni je brezbrižnost, ne sovraštvo.",
            "Nesreča v ljubezni, sreča pri igri.",
            "Ljubezen vlada brez meča, veže brez vrvi.",
            "Zaljubljenci imajo tudi pozimi pomlad.",
            "Prikupi se materi, če hočeš roko njene hčere.",
            "Če imaš nekoga rad, ti je ljubša še mačka iz njegove vasi.",
            "Ko potrka revščina na vrat, odide ljubezen skozi okno.",
            "Ženi se z ušesi, ne z očmi!",
            "Za ljubezen ni nobena pot predolga.",
            "Kjer je ljubezen, nič slabega ne škodi,kjer je ni, nič dobrega ne koristi.",
            "Če se mož in žena prepirata,je kačje gnezdo v hiši.",
            "Kri ni voda.",
            "Kakršen oče, takšen sin.",
            "Kakšen pastir, takšna čreda.",
            "Kri se ne zataji.",
            "Če mož ženo zmerja, jo otroci tepejo.",
            "Dokler je protje mlado, ga je lahko viti.",
            "Tašča pozablja, da je bila tudi sama snaha.",
            "Iver ne pade daleč od debla.",
            "Jabolko ne pade daleč od drevesa.",
            "Kakor mati prede, tako hči tke.",
            "Ti očeta do praga, sin tebe čez prag.",
            "Mož je glava družine, žena pa krona – zlata ali trnova.",
            "Kar mačka rodi, to miši lovi.",
            "Kakor jih starši uče, tako mladiči žvrgole.",
            "Od vola se uči orati volič.",
            "Na lesniki jabolko ne zraste.",
            "Drevo se po sadu spozna.",
            "Podobno se spodobnim druži.",
            "Enake sorte ptiči skup letijo.",
            "Vrana vrani ne izkljuje oči.",
            "Oče skopuh, sin goljuf.",
            "Vse se zmore, če se hoče.",
            "Brez dela ni jela.",
            "Brez muke ni moke.",
            "Lenoba je vseh grdob grdoba.",
            "Od rok do ust je dolga pot.",
            "Brez muje se še čevelj ne obuje.",
            "Pomagaj si sam in bog ti bo pomagal.",
            "Kar boš v mladosti sejal, boš v starosti žel.",
            "Kruha ne naredi moka ampak roka.",
            "Kdor neprestano gleda v oblake, ne bo nikoli žel.",
            "Ni vsak dan nedelja.",
            "Dobro storiti, pa ne okrog zvoniti.",
            "Kdor ne naredi nič za druge, ne naredi nič zasePameten kmet nameni za setev najboljše žito.",
            "Odloženo delo obtožuje, zamujeno kaznuje.",
            "Veliko besedi malo naredi.",
            "Čas setve še ni čas žetve.",
            "Kdor spi, rib ne ulovi.",
            "Koristi ni, če mlin stoji in jezik molči.",
            "Speča lisica kokoši ne ujame.",
            "Zvečer s kurami spat,zjutraj s ptički vstat,dan je treba iskat.",
            "Ne pričakuj sence od včeraj zasajenega drevesa.",
            "Hudo je, kadar se glad z žejo oženi.",
            "Iz te moke ne bo kruha.",
            "Še pes ima rad pri jedi mir.",
            "Bolje črn kos kruha, kakor prazna torba.",
            "Zrno do zrna pogača,kamen na kamen palača.",
            "Črne roke, bela pogača.",
            "S trebuhom za kruhom.",
            "Če kruhek pade ti na tla,poberi in poljubi ga.",
            "Kruha je pijan.",
            "Ljubezen gre skozi želodec.",
            "Naslikanega kruha ne moreš pojesti.",
            "Dobra jed se sama ponuja.",
            "Lakota je najboljši kuhar.",
            "Žganci bero mnoga masla.",
            "Pri kosti je mesa zadosti.",
            "Nobena juha se ne poje tako vroča kot se skuha.",
            "Eno jabolko na dan, odžene zdravnika stran.",
            "Zelje želodec samo nastelje.",
            "Jabolko je zjutraj zlato, opoldne srebrno, zvečer pa svinčeno.",
            "Brez krompirja ni kosila.",
            "Vse je šlo za med.",
            "Močnik je steber kranjske dežele.",
            "Velike ribe male žro.",
            "Še medveda naučijo z lakoto plesati.",
            "Voda za obraz, vino za dušo.",
            "V vinu je resnica.",
            "Kdor vino večerja, vodo zajtrkuje.",
            "Dobro jutro, žganje, zbogom pamet.",
            "Boljše je vino iz lonca, kakor voda iz zdenca.",
            "Kdor ne dela, naj ne je.",
            "Lakota je najboljša kuharica.",
            "Lakota je najboljša začimba.",
            "Kdor pije, ne da bi bil žejen in je,ne da bi bil lačen, zgodaj umre.",
            "Kdor je božji, je sit.",
            "Kdor gre na Dunaj, naj pusti trebuh zunaj.",
            "Zjutraj jej kot kralj, opoldne kot meščan, zvečer kot berač.",
            "Čas je zlato.",
            "Čas zaceli vse rane.",
            "Hiti počasi.",
            "Čas vse dozori.",
            "Ura zamujena ne vrne se nobena.",
            "S časom se celo čas obrne.",
            "Kdor zgodaj vstaja, mu časa preostaja.",
            "Rana ura, zlata ura.",
            "Kdor čas svoj prav obrne,se s čednostjo ogrne.",
            "Nobena pesem ni tako dolga,da se ne bi izpela.",
            "Noben dan ni tako dolg,da ne bi bilo večera.",
            "Lepota sivih las,je prav obrnjen čas.",
            "En dan poučuje drugega.",
            "Muzej je edini kraj, kjer lahko čas zavrtimo nazaj.",
            "Vse ure ranijo, a zadnja ubije.",
            "Dober glas ima čas.",
            "Slabe navade lahko premagaš samo danes, ne jutri.",
            "Boljši danes kos kakor jutri gos.",
            "Najmanj naredi kdor nima nikoli časa.",
            "Kdor prej pride, prej melje.",
            "Vsaka reč ima svoj čas.",
            "Kdor gladi koprivo, se opeče.",
            "Lakomnemu vedno nekaj manjka.",
            "Med dvema stoloma se na tla usedeš.",
            "Kdor ne uboga, ga tepe nadloga.",
            "Požrešnost jih več pogubi, kakor kuga, lakota in meč.",
            "Kdor druge opravlja na sebe pozablja.",
            "Kdor se zadnji smeje, se najslajše smeje.",
            "Kdor izbira, izbirek dobi.",
            "Najprej pometi pred svojim pragom.",
            "Zavist je sama najhujša kazen zavistnežu.",
            "Kdor visoko leta nizko pade.",
            "Nepošteno pridobljeno ne pride na drugo koleno.",
            "Kdor hitro sodi se hitro kesa.",
            "Kdor slabo vest ima, se sam izda.",
            "Kdor živi od laži, ga laž pokoplje.",
            "Lastni vesti ne ubežiš.",
            "Kdor druge sramoti, se sam osramoti.",
            "Kdor visoko viha nos,bo kmalu hodil bos.",
            "Najbolj prazen je tisti, ki je samega sebe poln.",
            "Zavist meri na druge, a zadene sebe.",
            "Lastna hvala medle konje jezdi.",
            "Lastna hvala, cena mala.",
            "Kdor veliko ve, malo verjame.",
            "Kar ti v glavi ostane, ti nihče ne vzame.",
            "Kjer neznanje se šopiri, tam hudič se ne umiri.",
            "Znanja ne zajemamo s korcem.",
            "Riba mora trikrat plavati:v vodi, olju in vinu.",
            "Nuja je mati iznajdljivosti.",
            "Več glav več ve.",
            "Obleka ne naredi človeka.",
            "Vol je vol, tudi če mu roge odbiješ.",
            "Znanje molči, neznanje kriči.",
            "Oblič mizarju, kopito čevljarju!",
            "Kovač ima klešče, da si rok ne opeče.",
            "Ni vse zlato kar se sveti.",
            "Bogastvo je modremu sluga, neumnemu gospodar.",
            "Ničesar ne odneseš s seboj na drugi svet.",
            "Veliko bogastvo, velika skrb.",
            "Nevesta bogata, je rada rogata.",
            "Ko zlato govori, beseda več ne drži.",
            "Revščina ima rada družbo.",
            "Čez sedem let vse prav pride.",
            "Kdor bolj ljubi denar kot obraz, izgubi oboje.",
            "Nagemu človeku ni mogoče seči v žep.",
            "Če sva si brata, mošnji si nista sestri.",
            "Za trgovca je domovina njegov žep.",
            "Strasti ki polnijo mošnjo, praznijo srce.",
            "Skopuh dvakrat klobaso skuha, preden jo proda.",
            "Višji ko je grad, večji v njem prebiva tat.",
            "Kdor vpraša ali je treba, ne da rad.",
            "Zlata veriga ne da svobode.",
            "Lakomnež ima velike oči in majhen želodec.",
            "Kdor veliko ima, po več zija.",
            "Kdor sebi ne privošči, tudi drugim ne.",
            "Kar se revežu da, v skrinji ne manjka.",
            "Kolikor bolj si sebi všeč, toliko manj si drugim."
        };

        public static string GetRandomProverb()
        {
            return _proverbs[new Random().Next(_proverbs.Length - 1)];
        }
    }
}
